<a href="https://colab.research.google.com/github/jumbokh/cgust-class/blob/main/python/codes/numpy_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape((4,2))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
c = a.reshape((2,4))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.reshape(-1)        # 轉換成一維陣列
print(b)                 # [1 2 3 4 5 6 7 8]
c = a.reshape((2,-1))    # 等同 a.reshape((2,4))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
d = a.reshape((2,2,-1))  # 等同 a.reshape((2,2,2))
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.flatten('C')    # [1 2 3 4 5 6 7 8]
c = a.flatten('F')    # [1 2 3 4 5 6 7 8]
b1 = np.ravel(a,'C')  # [1 3 5 7 2 4 6 8]
c1 = np.ravel(a,'K')  # [1 2 3 4 5 6 7 8]

In [6]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6],[7,8]])
b = a.flat[3]
print(b)    # 4

4


In [7]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = a.T
c = np.transpose(a)
print(b)
print(c)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [8]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.rollaxis(a,0,0)
c = np.rollaxis(a,1,0)
print(b)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [9]:
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.swapaxes(a,0,0)
c = np.swapaxes(a,0,1)
print(b)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [11]:
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.resize(a, (3,2))
print(b)

[[1 1]
 [1 2]
 [2 2]]


In [13]:
c = np.resize(a, (5,5))
print(c)

[[1 1 1 2 2]
 [2 1 1 1 2]
 [2 2 1 1 1]
 [2 2 2 1 1]
 [1 2 2 2 1]]


In [14]:
d = np.resize(a, (2,2))
print(d)

[[1 1]
 [1 2]]


In [15]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, 1)
c = np.append(a, [3,3,3])
print(b)   # [1 1 1 2 2 2 1]
print(c)   # [1 1 1 2 2 2 3 3 3]

[1 1 1 2 2 2 1]
[1 1 1 2 2 2 3 3 3]


In [16]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])
b = np.append(a, [[3,3,3],[4,4,4]],1)
print(b)

[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]


In [17]:
c = np.append(a, [[3,3,3],[4,4,4]],0)
print(c)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [18]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.insert(a, 1, [4,4])
c = np.insert(a, 2, [4,4])
print(b)   # [1 4 4 1 2 2 3 3]
print(c)   # [1 1 4 4 2 2 3 3]
d = np.insert(a, 2, [4,4], 0)
print(d)

[1 4 4 1 2 2 3 3]
[1 1 4 4 2 2 3 3]
[[1 1]
 [2 2]
 [4 4]
 [3 3]]


In [19]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.delete(a, 1)
c = np.delete(a, 2)
print(b)    # [1 3 4 5 6]
print(c)    # [1 2 4 5 6]
d = np.delete(a, 2, 0)
print(d)

[1 3 4 5 6]
[1 2 4 5 6]
[[1 2]
 [3 4]]


In [20]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.unique(a)
c = np.unique(a, return_index=True)
d = np.unique(a, return_inverse=True)
e = np.unique(a, return_counts=True)
print(b)   # [1 2 3]
print(c)   # (array([1, 2, 3]), array([0, 2, 4]))
print(d)   # (array([1, 2, 3]), array([0, 0, 1, 1, 2, 2]))
print(e)   # (array([1, 2, 3]), array([2, 2, 2]))

[1 2 3]
(array([1, 2, 3]), array([0, 2, 4]))
(array([1, 2, 3]), array([0, 0, 1, 1, 2, 2]))
(array([1, 2, 3]), array([2, 2, 2]))


## 填充一維陣列

In [21]:
import numpy as np
a = np.array([-2,-1,0,1,2])
print(np.pad(a,5))
# 左右各多出五個空格，填入 0
 # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]

print(np.pad(a,5,constant_values = (5,8)))
# 左右各多出五個空格，左邊填入 5，右邊填入 8
# [ 5  5  5  5  5 -2 -1  0  1  2  8  8  8  8  8]

print(np.pad(a,(1,5)))
# 左邊多出一個空格，右邊多出五個空格，填入 0
# [ 0 -2 -1  0  1  2  0  0  0  0  0]

print(np.pad(a,(1,5),constant_values = (5,8)))
# 左邊多出一個空格，右邊多出五個空格，左邊填入 5，右邊填入 8
# [ 5 -2 -1  0  1  2  8  8  8  8  8]

[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 5  5  5  5  5 -2 -1  0  1  2  8  8  8  8  8]
[ 0 -2 -1  0  1  2  0  0  0  0  0]
[ 5 -2 -1  0  1  2  8  8  8  8  8]


In [22]:
import numpy as np
a = np.array([-2,-1,0,1,2])
print(np.pad(a,5,mode='edge'))        # [-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
print(np.pad(a,5,mode='linear_ramp')) # [ 0  0  0 -1 -1 -2 -1  0  1  2  1  1  0  0  0]
print(np.pad(a,5,mode='maximum'))     # [ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
print(np.pad(a,5,mode='mean'))        # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
print(np.pad(a,5,mode='median'))      # [ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
print(np.pad(a,5,mode='minimum'))     # [-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
print(np.pad(a,5,mode='reflect'))     # [ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
print(np.pad(a,5,mode='symmetric'))   # [ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
print(np.pad(a,5,mode='wrap'))        # [-2 -1  0  1  2 -2 -1  0  1  2 -2 -1  0  1  2]

[-2 -2 -2 -2 -2 -2 -1  0  1  2  2  2  2  2  2]
[ 0 -1 -1 -2 -2 -2 -1  0  1  2  1  1  0  0  0]
[ 2  2  2  2  2 -2 -1  0  1  2  2  2  2  2  2]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[ 0  0  0  0  0 -2 -1  0  1  2  0  0  0  0  0]
[-2 -2 -2 -2 -2 -2 -1  0  1  2 -2 -2 -2 -2 -2]
[ 1  2  1  0 -1 -2 -1  0  1  2  1  0 -1 -2 -1]
[ 2  1  0 -1 -2 -2 -1  0  1  2  2  1  0 -1 -2]
[-2 -1  0  1  2 -2 -1  0  1  2 -2 -1  0  1  2]


### 填充多維陣列

In [23]:
import numpy as np
a = np.array([[1,1],[2,2]])
print(np.pad(a,2))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 2 2 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [24]:
print(np.pad(a,2,constant_values = (5,8)))

[[5 5 5 5 8 8]
 [5 5 5 5 8 8]
 [5 5 1 1 8 8]
 [5 5 2 2 8 8]
 [5 5 8 8 8 8]
 [5 5 8 8 8 8]]


In [25]:
print(np.pad(a,(1,2)))

[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 2 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [26]:
print(np.pad(a,(1,2),constant_values = (5,8)))

[[5 5 5 8 8]
 [5 1 1 8 8]
 [5 2 2 8 8]
 [5 8 8 8 8]
 [5 8 8 8 8]]


In [27]:
print(np.pad(a,2,mode='edge'))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [28]:
print(np.pad(a,2,mode='linear_ramp'))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 1 2 2 1 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]


In [29]:
print(np.pad(a,2,mode='maximum'))

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [30]:
print(np.pad(a,2,mode='mean'))

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [31]:
print(np.pad(a,2,mode='median'))

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [32]:
print(np.pad(a,2,mode='minimum'))

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [33]:
print(np.pad(a,2,mode='reflect'))

[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]


In [34]:
print(np.pad(a,2,mode='symmetric'))

[[2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]]


In [35]:
print(np.pad(a,2,mode='wrap'))

[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]]


### 分割陣列

In [36]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = np.array_split(a, 3)
c = np.split(a, 3)
print(b)  # [array([1, 2]), array([3, 4]), array([5, 6])]
print(c)  # [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [37]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
b = np.array_split(a, 2)
c = np.array_split(a, 2, 1)

print(b)  # [array([[1, 2],[3, 4]]), array([[5, 6]])]
print(c)  # [array([[1],[3],[5]]), array([[2],[4],[6]])]

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [38]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.hsplit(a, 3)
print(b)  # [array([[1],[2],[3]]), array([[1],[2],[3]]), array([[1],[2],[3]])]

[array([[1],
       [2],
       [3]]), array([[1],
       [2],
       [3]]), array([[1],
       [2],
       [3]])]


In [39]:
import numpy as np

a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.vsplit(a, 3)
print(b)   # [array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])]

[array([[1, 1, 1]]), array([[2, 2, 2]]), array([[3, 3, 3]])]


In [40]:
import numpy as np

a = np.array([1])
b = np.array([2,2])
c = np.array([3,3,3])
d = np.concatenate((a, b, c))
print(d)   # [1 2 2 3 3 3]

[1 2 2 3 3 3]


In [41]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])
b = np.array([[4,4],[5,5]])
c = np.concatenate((a, b))
print(c)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [42]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])      # 3x2 陣列
b = np.array([[4,4],[5,5],[6,6]])      # 3x2 陣列
# b = np.array([[4,4],[5,5],[6,6,6]])  # 如果 b 的形狀和 a 不同，會發生錯誤
c = np.concatenate((a, b), axis=0)     # axis 設定為 0
print(c)                               # 連接變成 6x2 陣列

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]


In [43]:
d = np.concatenate((a, b), axis=1)     # axis 設定為 1
print(d)                               # 連接變成 3x4 陣列

[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]


In [44]:
import numpy as np

a = np.array([1,1])
b = np.array([2,2])
c = np.array([3,3])
d = np.concatenate((a, b, c))
print(d)   # [1 1 2 2 3 3]

[1 1 2 2 3 3]


In [45]:
import numpy as np

a = np.array([[1,1],[2,2],[3,3]])  # 3x2 的陣列
b = np.array([[4,4],[5,5],[6,6]])  # 3x2 的陣列
c = np.stack((a, b), axis=0)       # axis 設定為 0
print(c)                           # 堆積成為 2x3x2 的陣列

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [46]:
d = np.stack((a, b), axis=1)       # axis 設定為 0
print(d)                           # 堆積成為 3x2x2 的陣列

[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]


In [47]:
a = np.array([[1,1],[2,2],[3,3]])   # 3x2 陣列
b = np.array([[4,4],[5,5],[6,6]])   # 3x2 陣列
c = np.hstack((a, b))               # 水平合併
print(c)                            # 變成 3x4 的陣列

[[1 1 4 4]
 [2 2 5 5]
 [3 3 6 6]]


In [48]:
d = np.vstack((a, b))               # 垂直合併
print(d)                            # 變成 6x2 的陣列

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]


### 陣列排序

In [49]:
a = np.array([5,3,4,2,1,6,7,9,8])
b = np.sort(a)
print(b)    # [1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [50]:
import numpy as np

arr = [
  [2,3],
  [5,2],
  [3,1]
]
a = np.array(arr)
b = np.sort(a)   # 針對最後一軸排序 ( -1，二維陣列就是 1 )，所以只會排列 2 和 3、5 和 2、3 和 1
print(b)

[[2 3]
 [2 5]
 [1 3]]


In [51]:
c = np.sort(a, axis=None)   # axis 設定 None 會打散並排序為一維陣列
print(c)                    # [1 2 2 3 3 5]
d = np.sort(a,axis=0)       # 針對垂直維度 ( 0 軸 ) 由小到大排序，所有項目都是從小到大
print(d)

[1 2 2 3 3 5]
[[2 1]
 [3 2]
 [5 3]]


In [52]:
e = np.sort(a,axis=1)       # 因為是二維陣列，axis 設定 1 等同 np.sort(a)
print(e)

[[2 3]
 [2 5]
 [1 3]]


In [53]:
import numpy as np

arr = [
  ('oxxo',200),
  ('gkpen',100),
  ('frank',300)
]
dt = np.dtype([('name','S10'),('num',int)])
a = np.array(arr, dtype = dt)
b = np.sort(a,order='name')    # 針對 name 欄位排序
c = np.sort(a,order='num')     # 針對 um 欄位排序
print(b)      # [(b'frank', 300) (b'gkpen', 100) (b'oxxo', 200)]
print(c)      # [(b'gkpen', 100) (b'oxxo', 200) (b'frank', 300)]

[(b'frank', 300) (b'gkpen', 100) (b'oxxo', 200)]
[(b'gkpen', 100) (b'oxxo', 200) (b'frank', 300)]


In [54]:
import numpy as np

arr = [
  [2,3,7],
  [5,2,6],
  [3,1,2]
]
a = np.array(arr)
b = np.argsort(a)
print(b)

[[0 1 2]
 [1 0 2]
 [1 2 0]]


In [55]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = np.array(['e','d','a','c','g','h','f','b'])
c = np.lexsort((a,b))    # b 先排序，然後 a 按照 b 的順序排序後回傳索引值
d = np.lexsort((b,a))    # a 先排序，然後 b 按照 a 的順序排序後回傳索引值
print(c)    # [2 7 3 1 0 6 4 5]   對應 3 8 4 2 1 7 5 6
print(d)    # [0 1 2 3 4 5 6 7]

[2 7 3 1 0 6 4 5]
[0 1 2 3 4 5 6 7]


In [56]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = np.argmax(a)
c = np.argmin(a)
print(b)    # 7   對應 8
print(c)    # 0   對應 1

7
0


## 廣播
### NumPy 裡有個處理陣列的特別方法：廣播，意思是將「比較小的陣列內容，廣播到比較大的陣列中」，產生互相兼容的尺寸形狀，NumPy 的廣播實際使用 C 語言運作，可以有效的運用記憶體和運算，進一步提高程式運作的效率，這篇教學將會介紹 NumPy 廣播的用法。

In [57]:
import numpy as np

a = np.array([1,2,3,4])   # 1x4 陣列
b = 2                     # 廣播單一數字 2
print(a+b)                # [3 4 5 6]
print(a-b)                # [-1  0  1  2]
print(a*b)                # [2 4 6 8]
print(a%b)                # [1 0 1 0]

c = np.array([[1,2,3],[4,5,6]])  # 2x3 陣列
print(c+b)    # [[3 4 5] [6 7 8]]
print(c-b)    # [[-1  0  1] [ 2  3  4]]
print(c*b)    # [[ 2  4  6] [ 8 10 12]]
print(c%b)    # [[1 0 1] [0 1 0]]

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[1 0 1 0]
[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[1 0 1]
 [0 1 0]]


## 廣播陣列
#### 如果要將某個陣列廣播到另外一個陣列，同樣能單純透過數學運算式進行計算後廣播，但必須注意在「同一個軸 ( 維度 )」上的數量必須相等或等於 1，不然廣播時會發生錯誤

In [58]:
import numpy as np

a = np.array([[1,1,1],[2,2,2]])   # 2x3 陣列
b = np.array([1,2,3])             # 1x3 陣列
print(a+b)     # [[2 3 4] [3 4 5]]
print(a-b)     # [[ 0 -1 -2] [ 1  0 -1]]
print(a*b)     # [[1 2 3] [2 4 6]]
print(a%b)     # [[0 1 1] [0 0 2]]

c = np.array([[1,1,1],[2,2,2],[3,3,3]])   # 3x3 陣列
d = np.array([[1],[2],[3]])               # 3x1 陣列
print(c+d)     # [[2 2 2] [4 4 4] [6 6 6]]
print(c-d)     # [[0 0 0] [0 0 0] [0 0 0]]
print(c*d)     # [[1 1 1] [4 4 4] [9 9 9]]
print(c%d)     # [[0 0 0] [0 0 0] [0 0 0]]

[[2 3 4]
 [3 4 5]]
[[ 0 -1 -2]
 [ 1  0 -1]]
[[1 2 3]
 [2 4 6]]
[[0 1 1]
 [0 0 2]]
[[2 2 2]
 [4 4 4]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [4 4 4]
 [9 9 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [59]:
import numpy as np
a = np.array([[1,1,1],[2,2,2]])   # 2x3 陣列
b = np.array([[3,3,3],[4,4,4]])   # 2x3 陣列
print(a+b)     # [[4 4 4] [6 6 6]]
print(a-b)     # [[-2 -2 -2] [-2 -2 -2]]
print(a*b)     # [[3 3 3] [8 8 8]]
print(a%b)     # [[1 1 1] [2 2 2]]

[[4 4 4]
 [6 6 6]]
[[-2 -2 -2]
 [-2 -2 -2]]
[[3 3 3]
 [8 8 8]]
[[1 1 1]
 [2 2 2]]


## 字串操作處理
#### 在 Python 裡如果遇到資料中的文字處理狀況，通常會使用迴圈的方式慢慢處理，然而 NumPy 提供許多處理與操作陣列裡文字的方法，能夠很簡單的進行分割、合併、置換...等字串處理，也能夠快速地進行內容判斷並回傳布林值，這篇教學會介紹 NumPy 操作與處理字串的方法。

#### 建立字串陣列
#### 透過 NumPy 建立字串陣列的方法，可以建立由字串所組成的新陣列。

In [60]:
from numpy import char

a = char.array(['a','b','c. \n', 1])     # 換行符號和空白會被取代，數字轉換成文字
b = char.asarray(['a','b','c. \n',1])    # 換行符號和空白會被取代，數字轉換成文字
print(a)                                 # ['a' 'b' 'c.' '1']
print(b)                                 # ['a' 'b' 'c.' '1']
c1 = char.chararray((3,3))               # 產生一個 3x3 的文字陣列，內容放入 string
c2 = char.chararray((3,3), unicode=True) # 產生一個 3x3 的文字陣列，內容放入 unicode 字串
print(c1)                                # [[b'\xa0' b'\x10' ''] [b'\xe6' b'!' b'V'] ['' '' '']]
print(c2)                                # [['' '' ''] ['' '' ''] ['' '' '']]
d = char.chararray((3,3), unicode=True)  # 產生一個 3x3 的文字陣列，內容放入 unicode 字串
d[:] = 'a'                               # 將內容全換成字母 a
print(d)                                 # [['a' 'a' 'a'] ['a' 'a' 'a'] ['a' 'a' 'a']]

['a' 'b' 'c.' '1']
['a' 'b' 'c.' '1']
[[b'-' b'\xdc' b'\xb0']
 ['' b'\xc9' b'Z']
 ['' '' '']]
[['' '' '']
 ['' '' '']
 ['' '' '']]
[['a' 'a' 'a']
 ['a' 'a' 'a']
 ['a' 'a' 'a']]


## 組合、重複字串
#### 透過 NumPy 組合、重複字串的方法，可以組合不同的字串陣列，或重複字串內容，成為新的陣列。

In [61]:
from numpy import char

a = np.array(['a','b','c','d'])      # 1x4 一維陣列
b = np.array(['w','x','y','z'])      # 1x4 一維陣列
print(char.add(a,b))                 # ['aw' 'bx' 'cy' 'dz']
print(char.multiply(a,3))            # ['aaa' 'bbb' 'ccc' 'ddd']

c = np.array([['a','b'],['c','d']])  # 2x2 二維陣列
d = np.array([['w','x'],['y','z']])  # 2x2 二維陣列
print(char.add(c,d))                 # [['aw' 'bx'] ['cy' 'dz']]
print(char.multiply(c,3))            # [['aaa' 'bbb'] ['ccc' 'ddd']]

['aw' 'bx' 'cy' 'dz']
['aaa' 'bbb' 'ccc' 'ddd']
[['aw' 'bx']
 ['cy' 'dz']]
[['aaa' 'bbb']
 ['ccc' 'ddd']]


## 對齊、補齊字串
#### 透過 NumPy 對齊、補齊字串的方法，可以對齊字串內容，或使用特定字元補齊內容，成為新的陣列。

In [62]:
from numpy import char

a = np.array(['a','bb','ccc','dddd'])
print(char.center(a, 10, '+'))    # 置中對齊，空白補 +
                                  # ['++++a+++++' '++++bb++++' '+++ccc++++' '+++dddd+++']
print(char.ljust(a, 10, '+'))     # 置左對齊，空白補 +
                                  # ['a+++++++++' 'bb++++++++' 'ccc+++++++' 'dddd++++++']
print(char.rjust(a, 10, '+'))     # 置右對齊，空白補 +
                                  # ['+++++++++a' '++++++++bb' '+++++++ccc' '++++++dddd']
print(char.zfill(a, 10))          # 置右對齊，空白補 0
                                  # ['000000000a' '00000000bb' '0000000ccc' '000000dddd']

['++++a+++++' '++++bb++++' '+++ccc++++' '+++dddd+++']
['a+++++++++' 'bb++++++++' 'ccc+++++++' 'dddd++++++']
['+++++++++a' '++++++++bb' '+++++++ccc' '++++++dddd']
['000000000a' '00000000bb' '0000000ccc' '000000dddd']


## 移除、分割字串
#### 透過 NumPy 移除、分割字串的方法，可以移除字串內特定文字，或根據特定字元分割字串，成為新的陣列。

In [63]:
from numpy import char

a = np.array(['aaa','aa\nbb','bb\naa','abab'])
print(char.lstrip(a,'a'))     # 移除左側所有 a ( 遇到不是 a 就停止 )
                              # ['' '\nbb' 'bb\naa' 'bab']
print(char.rstrip(a,'a'))     # 移除右側所有 a ( 遇到不是 a 就停止 )
                              # ['' 'aa\nbb' 'bb\n' 'abab']
print(char.strip(a,'a'))      # 移除左右所有 a ( 遇到不是 a 就停止 )
                              # ['' '\nbb' 'bb\n' 'bab']
print(char.partition(a,'a'))  # 以 b 的左側分割元素 ( 分割後會包含 b )
                              # [['' 'a' 'aa'] ['' 'a' 'a\nbb'] ['bb\n' 'a' 'a'] ['' 'a' 'bab']]
print(char.rpartition(a,'a')) # 以 b 的右側分割元素 ( 分割後會包含 b )
                              # [['aa' 'a' ''] ['a' 'a' '\nbb'] ['bb\na' 'a' ''] ['ab' 'a' 'b']]
print(char.split(a,'a'))      # 以 b 的左側分割元素 ( 分割後會不包含 b )
                              # [list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', '']) list(['', 'b', 'b'])]
print(char.rsplit(a,'a'))     # 以 b 的右側分割元素 ( 分割後會不包含 b )
                              # [list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', '']) list(['', 'b', 'b'])]
print(char.splitlines(a))     # 根據換行符號分割元素
                              # [list(['aaa']) list(['aa', 'bb']) list(['bb', 'aa']) list(['abab'])]

['' '\nbb' 'bb\naa' 'bab']
['' 'aa\nbb' 'bb\n' 'abab']
['' '\nbb' 'bb\n' 'bab']
[['' 'a' 'aa']
 ['' 'a' 'a\nbb']
 ['bb\n' 'a' 'a']
 ['' 'a' 'bab']]
[['aa' 'a' '']
 ['a' 'a' '\nbb']
 ['bb\na' 'a' '']
 ['ab' 'a' 'b']]
[list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', ''])
 list(['', 'b', 'b'])]
[list(['', '', '', '']) list(['', '', '\nbb']) list(['bb\n', '', ''])
 list(['', 'b', 'b'])]
[list(['aaa']) list(['aa', 'bb']) list(['bb', 'aa']) list(['abab'])]


## 替換、轉換字串
#### 透過 NumPy 替換、轉換字串的方法，可以替換字串內的特定文字，或進行大小寫的轉換，成為新的陣列。

In [64]:
from numpy import char

a = np.array(['abc','ABC','abc xyz'])
print(char.capitalize(a))           # 一段文字的字首字母轉大寫
                                    # ['Abc' 'Abc' 'Abc xyz']
print(char.lower(a))                # 字母全部轉小寫
                                    # ['abc' 'abc' 'abc xyz']
print(char.upper(a))                # 字母全部轉大寫
                                    # ['ABC' 'ABC' 'ABC XYZ']
print(char.swapcase(a))             # 字母大小寫互換
                                    # ['ABC' 'abc' 'ABC XYZ']
print(char.title(a))                # 所有單字字首轉大寫
                                    # ['Abc' 'Abc' 'Abc Xyz']
print(char.join('-',a))             # 所有字母之間加上 -
                                    # ['a-b-c' 'A-B-C' 'a-b-c- -x-y-z']
print(char.join(['-',':','+'],a))   # 在不同項目裡，所有字母間加上對應的符號
                                    # ['a-b-c' 'A:B:C' 'a+b+c+ +x+y+z']
print(char.replace(a,'abc','mno'))  # 置換 abc 為 mno
                                    # ['mno' 'ABC' 'mno xyz']
c = char.encode(a)                  # 換成 unicode
print(c)                            # [b'abc' b'ABC' b'abc xyz']
print(char.decode(c))               # 換成 utf8
                                    # ['abc' 'ABC' 'abc xyz']

['Abc' 'Abc' 'Abc xyz']
['abc' 'abc' 'abc xyz']
['ABC' 'ABC' 'ABC XYZ']
['ABC' 'abc' 'ABC XYZ']
['Abc' 'Abc' 'Abc Xyz']
['a-b-c' 'A-B-C' 'a-b-c- -x-y-z']
['a-b-c' 'A:B:C' 'a+b+c+ +x+y+z']
['mno' 'ABC' 'mno xyz']
[b'abc' b'ABC' b'abc xyz']
['abc' 'ABC' 'abc xyz']


## 尋找字串、計算字串長度
#### 透過 NumPy 尋找字串、計算字串長度的方法，可以尋找字串內的特定文字，或計算字串長度，成為新的陣列。

In [65]:
from numpy import char

a = np.array(['abab','aabb','bbaa','xyz'])
print(char.find(a,'a'))       # 從左邊開始找到字母 a 的位置
                              # [ 0  0  2 -1]
print(char.rfind(a,'a'))      # 從右邊開始找到字母 a 的位置
                              # [ 2  1  3 -1]
print(char.count(a,'a',0,2))  # 計算出現幾次字母 a
                              # [1 2 0 0]
print(char.count(a,'a',1,3))  # [1 1 1 0]
print(char.str_len(a))        # [4 4 4 3]

[ 0  0  2 -1]
[ 2  1  3 -1]
[1 2 0 0]
[1 1 1 0]
[4 4 4 3]


## 判斷字串
#### 透過 NumPy 判斷字串的方法，可以判斷字串的內容、大小寫、開頭或結尾，並回傳布林值所組成的新陣列。

In [66]:
from numpy import char


a = np.array(['abc','ABC','Abc Cba','abc123','123',''])
b = np.array(['abc','123','xyz','abc123','123',''])
print(char.isalpha(a))         # 只有字母 True，有包含數字或其他符號 False
                               # [ True  True False False False False]
print(char.isalnum(a))         # 只有字母和數字 True，有包含其它符號 False
                               # [ True  True False  True  True False]
print(char.isdecimal(a))       # 只有十進位數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isdigit(a))         # 只有純數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isnumeric(a))       # 只有純數字 True，有包含其它符號或字母 False
                               # [False False False False  True False]
print(char.isspace(a))         # 只有空白符號 True，有包含字母、數字或其它符號 False
                               # [False False False False False False]
print(char.islower(a))         # 至少有一個字母且都小寫 True，有包含大寫 False
                               # [ True False False  True False False]
print(char.isupper(a))         # 至少有一個字母且都大寫 True，有包含小寫 False
                               # [False  True False False False False]
print(char.istitle(a))         # 字串是 title ( 每個單字的字首都大寫 ) True，否則 False
                               # [False False  True False False False]
print(char.startswith(a,'a'))  # a 開頭的字串 True，否則 False
                               # [ True False False  True False False]
print(char.endswith(a,'a'))    # a 結尾的字串 True，否則 False
                               # [False False  True False False False]
print(char.equal(a,b))         # a 陣列和 b 陣列元素相等 True，否則 False
                               # [ True False False  True  True  True]
print(char.not_equal(a,b))     # a 陣列和 b 陣列元素不相等 True，否則 False
                               # [False  True  True False False False]
print(char.greater_equal(a,b)) # a 陣列和 b 陣列元素 的 unicode 大於且相等 True，否則 False
                               # [ True  True False  True  True  True]
print(char.less_equal(a,b))    # a 陣列和 b 陣列元素 的 unicode 小於且相等 True，否則 False
                               # [ True False  True  True  True  True]
print(char.greater(a,b))       # a 陣列和 b 陣列元素 的 unicode 大於 True，否則 False
                               # [False  True False False False False]
print(char.less(a,b))          # a 陣列和 b 陣列元素 的 unicode 小於 True，否則 False
                               # [False False  True False False False]
print(char.compare_chararrays(a,b,'>=',True))  # a 陣列和 b 陣列元素 的 unicode 大於等於 True，否則 False
                               # [ True  True False  True  True  True]

[ True  True False False False False]
[ True  True False  True  True False]
[False False False False  True False]
[False False False False  True False]
[False False False False  True False]
[False False False False False False]
[ True False False  True False False]
[False  True False False False False]
[False False  True False False False]
[ True False False  True False False]
[False False  True False False False]
[ True False False  True  True  True]
[False  True  True False False False]
[ True  True False  True  True  True]
[ True False  True  True  True  True]
[False  True False False False False]
[False False  True False False False]
[ True  True False  True  True  True]
